"use client";

import { useMemo, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import GradientPageHeader from "@/components/bakery/shared/GradientPageHeader";
import StatusBadge from "@/components/bakery/shared/StatusBadge";
import PaymentBadge from "@/components/bakery/shared/PaymentBadge";
import PriceSummaryCard from "@/components/bakery/bookings/PriceSummaryCard";
import OrderStepper from "@/components/bakery/shared/OrderStepper";
import OrderTimeline from "@/components/bakery/shared/OrderTimeline";
import { Button } from "@/components/ui/button";
import { Select } from "@/components/ui/select";
import { CheckCircle2, FileText, Printer } from "lucide-react";
import { useOrders } from "@/components/bakery/store";
import { useParams } from "next/navigation";
import { formatCurrency } from "@/components/orders/formatters";
import { toast } from "sonner";

export default function OrderDetailPage() {
  const {
    orders,
    approveOrder,
    updateOrderSchedule,
    updatePaymentStatus,
    getCustomerMessagePreview,
  } = useOrders();
  const params = useParams();
  const orderId = typeof params?.id === "string" ? params.id : "";
  const [rescheduleDate, setRescheduleDate] = useState("");
  const [rescheduleSlot, setRescheduleSlot] = useState("09:00");

  const order = useMemo(
    () => orders.find((item) => item.id === orderId),
    [orders, orderId]
  );

  const slotLimitPerHour = 3;
  const blockedDates = ["2026-03-31", "2026-04-18"];
  const deliverySlots = ["08:00", "09:00", "10:00", "11:00", "13:00", "14:00", "15:00", "16:00"];

  const effectiveDate = rescheduleDate || order?.deliveryDate || "";
  const effectiveSlot = rescheduleSlot || order?.deliverySlot || "09:00";

  const slotUsage = useMemo(() => {
    if (!effectiveDate || !effectiveSlot) return 0;
    return orders.filter(
      (item) =>
        item.id !== orderId &&
        item.deliveryDate === effectiveDate &&
        item.deliverySlot === effectiveSlot &&
        !["Cancelled", "Completed"].includes(item.orderStatus)
    ).length;
  }, [orders, orderId, effectiveDate, effectiveSlot]);

  const isBlockedDate = Boolean(
    effectiveDate &&
      (blockedDates.includes(effectiveDate) || new Date(effectiveDate).getDay() === 0)
  );
  const isSlotFull = slotUsage >= slotLimitPerHour;

  const totalPrice = order?.totalPrice ?? 0;
  const messagePreview = order ? getCustomerMessagePreview(order.id) : "";

  const handleApprove = () => {
    if (!order) return;
    approveOrder(order.id);
  };

  const handleReschedule = () => {
    if (!order) return;
    if (!effectiveDate || !effectiveSlot || isBlockedDate || isSlotFull) return;
    updateOrderSchedule(order.id, effectiveDate, effectiveSlot);
  };

  const handlePrintLabel = () => {
    if (!order) return;
    const itemLines = (order.items ?? [])
      .map((item) => `${item.quantity}x ${item.productName} (${item.size})`)
      .join("<br />");
    const addressLines = (order.deliveryAddresses ?? [])
      .map((address) => `${address.label} - ${address.addressLine}`)
      .join("<br />");

    const printWindow = window.open("", "_blank", "width=420,height=720");
    if (!printWindow) return;
    printWindow.document.write(`
      <html>
        <head>
          <title>Print Label</title>
          <style>
            body { font-family: Arial, sans-serif; margin: 0; padding: 16px; color: #111827; }
            .label { border: 1px dashed #111827; padding: 12px; width: 320px; }
            .title { font-size: 14px; font-weight: 700; margin-bottom: 10px; }
            .row { font-size: 12px; margin-bottom: 6px; }
            .muted { color: #4b5563; font-size: 11px; }
          </style>
        </head>
        <body>
          <div class="label">
            <div class="title">ORDER LABEL</div>
            <div class="row"><strong>Code:</strong> ${order.resi || order.bookingCode || order.id}</div>
            <div class="row"><strong>Name:</strong> ${order.customerName}</div>
            <div class="row"><strong>Phone:</strong> ${order.customerPhone || "-"}</div>
            <div class="row"><strong>Address:</strong><br />${addressLines || "-"}</div>
            <div class="row"><strong>Delivery:</strong> ${order.deliveryDate} ${order.deliverySlot}</div>
            <div class="row"><strong>Items:</strong><br />${itemLines || "-"}</div>
            <div class="row"><strong>Total:</strong> ${formatCurrency(order.totalPrice ?? 0)}</div>
            <div class="muted">Generated by Bakery OMS</div>
          </div>
          <script>window.print();window.close();</script>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  const handleCopyMessage = async () => {
    try {
      await navigator.clipboard.writeText(messagePreview);
      toast.success("Customer message copied");
    } catch {
      toast.error("Failed to copy message");
    }
  };

  if (!order) {
    return (
      <div className="space-y-6 pb-10">
        <GradientPageHeader
          title="Order Detail"
          description="We could not find this booking."
          icon={FileText}
        />
        <div className="rounded-xl border border-dashed border-gray-200 bg-gray-50/60 px-4 py-6 text-center text-sm text-gray-500">
          Order not found. Please return to the bookings list.
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6 pb-10">
      <GradientPageHeader
        title="Order Detail"
        description="Review the booking, confirm details, and move the order forward."
        icon={FileText}
        actions={
          <Button
            onClick={handleApprove}
            disabled={!(["Inquiry", "Quoted", "DP Paid"].includes(order.orderStatus))}
            className={
              !(["Inquiry", "Quoted", "DP Paid"].includes(order.orderStatus))
                ? "gap-2"
                : "gap-2 bg-indigo-600 text-white hover:bg-indigo-700 focus-visible:ring-indigo-500"
            }
            variant={!(["Inquiry", "Quoted", "DP Paid"].includes(order.orderStatus)) ? "secondary" : "default"}
          >
            <CheckCircle2 size={16} />
            {!(["Inquiry", "Quoted", "DP Paid"].includes(order.orderStatus)) ? "Approved" : "Approve Order"}
          </Button>
        }
      />

      {order.orderStatus === "Confirmed" && (
        <div className="space-y-2 rounded-xl border border-indigo-100 bg-indigo-50 px-4 py-3 text-sm font-semibold text-indigo-700">
          <p>Order approved. Booking code generated: {order.resi || order.bookingCode}</p>
          <p className="text-xs font-medium text-indigo-600">
            {order.simulations?.whatsappSent ? "WhatsApp sent" : "WhatsApp pending"} | {" "}
            {order.simulations?.calendarEventCreated ? "Calendar event created" : "Calendar event pending"}
          </p>
        </div>
      )}

      <OrderStepper status={order.orderStatus} />

      <div className="grid gap-6 lg:grid-cols-[2fr,1fr]">
        <div className="space-y-6">
          <Card className="rounded-xl shadow-sm">
            <CardHeader className="p-6 pb-2">
              <CardTitle>Customer Info</CardTitle>
            </CardHeader>
            <CardContent className="space-y-2 px-6 pb-6 pt-0 text-sm text-gray-700">
              <p>
                <span className="font-semibold">Name:</span> {order.customerName}
              </p>
              <p>
                <span className="font-semibold">Phone:</span> {order.customerPhone ?? "-"}
              </p>
              <p>
                <span className="font-semibold">Address:</span> {order.customerAddress ?? "-"}
              </p>
              <Button
                type="button"
                variant="outline"
                className="mt-2 h-8 gap-1 border-indigo-200 text-indigo-700 hover:bg-indigo-50"
                onClick={handlePrintLabel}
              >
                <Printer size={14} />
                Print Label
              </Button>
            </CardContent>
          </Card>

          <Card className="rounded-xl shadow-sm">
            <CardHeader className="p-6 pb-2">
              <CardTitle>Order Details</CardTitle>
            </CardHeader>
            <CardContent className="space-y-2 px-6 pb-6 pt-0 text-sm text-gray-700">
              <div>
                <p className="mb-1 font-semibold">Items:</p>
                <div className="space-y-1">
                  {(order.items ?? []).map((item) => (
                    <p key={item.id}>
                      {item.quantity}x {item.productName} ({item.category} / {item.subcategory} / {item.size})
                    </p>
                  ))}
                </div>
              </div>
              <p>
                <span className="font-semibold">Delivery Date:</span> {order.deliveryDate}
              </p>
              <p>
                <span className="font-semibold">Delivery Slot:</span> {order.deliverySlot}
              </p>
              <p>
                <span className="font-semibold">Add-ons:</span> {order.addOns ?? "-"}
              </p>
              <p>
                <span className="font-semibold">Notes:</span> {order.notes ?? "-"}
              </p>
              <div>
                <p className="mb-1 font-semibold">Delivery Addresses:</p>
                <div className="space-y-1">
                  {(order.deliveryAddresses ?? []).map((address) => (
                    <p key={address.id}>
                      {address.label} - {address.area}: {address.addressLine}
                    </p>
                  ))}
                </div>
              </div>
            </CardContent>
          </Card>

          <Card className="rounded-xl shadow-sm">
            <CardHeader className="p-6 pb-2">
              <CardTitle>Reschedule Delivery</CardTitle>
            </CardHeader>
            <CardContent className="space-y-3 px-6 pb-6 pt-0 text-sm text-gray-700">
              <div className="grid gap-3 sm:grid-cols-2">
                <label className="grid gap-2">
                  <span className="text-xs font-semibold uppercase tracking-wide text-gray-500">Delivery Date</span>
                  <input
                    type="date"
                    value={rescheduleDate}
                    onChange={(event) => setRescheduleDate(event.target.value)}
                    className="h-10 rounded-xl border border-gray-200 px-3"
                  />
                </label>
                <label className="grid gap-2">
                  <span className="text-xs font-semibold uppercase tracking-wide text-gray-500">Delivery Slot</span>
                  <Select value={rescheduleSlot} onChange={(event) => setRescheduleSlot(event.target.value)}>
                    {deliverySlots.map((slot) => (
                      <option key={slot} value={slot}>{slot}</option>
                    ))}
                  </Select>
                </label>
              </div>
              {(isBlockedDate || isSlotFull) && (
                <div className="rounded-xl border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-700">
                  {isBlockedDate
                    ? "Selected date is blocked/unavailable."
                    : `Slot full (${slotUsage}/${slotLimitPerHour}). Choose another time.`}
                </div>
              )}
              <Button
                type="button"
                variant="outline"
                className="border-indigo-200 text-indigo-700 hover:bg-indigo-50"
                disabled={!rescheduleDate || isBlockedDate || isSlotFull}
                onClick={handleReschedule}
              >
                Save Reschedule
              </Button>
            </CardContent>
          </Card>

          <Card className="rounded-xl shadow-sm">
            <CardHeader className="p-6 pb-2">
              <CardTitle>Customer Message Preview</CardTitle>
            </CardHeader>
            <CardContent className="space-y-2 px-6 pb-6 pt-0 text-sm text-gray-700">
              <div className="rounded-xl border border-indigo-100 bg-indigo-50 px-4 py-3 whitespace-pre-wrap">
                {messagePreview}
              </div>
              <Button
                type="button"
                variant="outline"
                className="border-indigo-200 text-indigo-700 hover:bg-indigo-50"
                onClick={handleCopyMessage}
              >
                Copy Message
              </Button>
            </CardContent>
          </Card>
        </div>

        <div className="space-y-6">
          <PriceSummaryCard
            basePrice={order.basePrice ?? 0}
            addOnTotal={order.addOnTotal ?? 0}
            deliveryFee={(order.deliveryFee ?? 0) + (order.manualAdjustment ?? 0)}
            totalPrice={totalPrice}
          />
          <Card className="rounded-xl shadow-sm">
            <CardHeader className="p-6 pb-2">
              <CardTitle>Status</CardTitle>
            </CardHeader>
            <CardContent className="space-y-3 px-6 pb-6 pt-0">
              <div className="flex items-center justify-between text-sm text-gray-600">
                <span>Payment Status</span>
                <PaymentBadge status={order.paymentStatus} />
              </div>
              <Select
                value={order.paymentStatus}
                onChange={(event) => updatePaymentStatus(order.id, event.target.value as "Pending" | "DP Paid" | "Paid")}
              >
                <option value="Pending">Pending</option>
                <option value="DP Paid">DP Paid</option>
                <option value="Paid">Paid</option>
              </Select>
              <div className="flex items-center justify-between text-sm text-gray-600">
                <span>Order Status</span>
                <StatusBadge status={order.orderStatus} />
              </div>
              <div className="flex items-center justify-between text-sm text-gray-600">
                <span>DP</span>
                <span className="font-semibold text-gray-900">Rp {Number(order.downPaymentAmount ?? 0).toLocaleString("id-ID")}</span>
              </div>
              <div className="flex items-center justify-between text-sm text-gray-600">
                <span>Remaining</span>
                <span className="font-semibold text-gray-900">Rp {Number(order.remainingBalance ?? 0).toLocaleString("id-ID")}</span>
              </div>
            </CardContent>
          </Card>

          <OrderTimeline
            status={order.orderStatus}
            deliveryDate={order.deliveryDate}
            history={order.statusHistory}
          />
        </div>
      </div>
    </div>
  );
}
